# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortune',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fortunes', to=settings.AUTH_USER_MODEL),
        ),
    ]
