# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160304_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortune',
            name='created',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='active',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='updated',
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
    ]
